[build]
  publish = "."
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-image-optim" # Example plugin for image optimization

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
